#!/bin/zsh

## for better results, also include this in /etc/security/pam_env.conf :
# XDG_CACHE_HOME DEFAULT=@{HOME}/.cache
# XDG_CONFIG_HOME DEFAULT=@{HOME}/.config
# XDG_DATA_HOME DEFAULT=@{HOME}/.local/share
# XDG_STATE_HOME DEFAULT=@{HOME}/.local/state

export XDG_CACHE_HOME=${HOME}/.cache
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state

# XDG compliance fixes
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export GOPATH="${XDG_DATA_HOME}/go"
export GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"
export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node_repl_history"
export NVM_DIR="${XDG_DATA_HOME}/nvm"
export PNPM_HOME="${XDG_DATA_HOME}/pnpm"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export WINEPREFIX="${XDG_DATA_HOME}/wine"

# note: remember to add a symlink at $ZDOTDIR/.zshenv to this file changes can
# 	be applied without a restart.
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

export EDITOR='nvim'

export LESS=' -R '
export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"

. "$CARGO_HOME/env"

